# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: check-symlinks
    -   id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: |
            (?x)(
                ^example/large/file.csv |
                ^example/large/sklearn-model.pkl
            )
    -   id: requirements-txt-fixer
    -   id: forbid-new-submodules
    # -   id: no-commit-to-branch
    #     args: ["--branch=main"]
    # -   id: detect-aws-credentials
    -   id: detect-private-key

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [
            --fix,
            --exit-non-zero-on-fix,
            --config=./pyproject.toml,
        ]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: "v1.10.0"
#     hooks:
#     -   id: mypy
#         args: [
#             --no-strict-optional,
#             --ignore-missing-imports,
#             --config-file=./pyproject.toml,
#         ]

# -   repo: https://github.com/psf/black
#     rev: "24.4.2"
#     hooks:
#     -   id: black
#         args:
#         -   --config=./pyproject.toml,

